# Generated by Django 2.2.4 on 2019-10-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='to',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
