# Generated by Django 2.2.4 on 2019-10-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
