# Generated by Django 2.2.4 on 2019-10-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20191006_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='tname',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='to',
        ),
    ]
