# Generated by Django 2.2.4 on 2019-10-19 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('comments', '0005_auto_20191006_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sap',
            field=models.ForeignKey(default='', max_length=15, on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
