# Generated by Django 2.2.4 on 2019-10-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20191019_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='sap',
        ),
    ]
