# Generated by Django 2.2.4 on 2019-09-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('questionid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('questions', models.CharField(max_length=5000)),
                ('a', models.CharField(max_length=5000)),
                ('b', models.CharField(max_length=5000)),
                ('c', models.CharField(max_length=5000)),
                ('d', models.CharField(max_length=5000)),
                ('correct', models.CharField(max_length=5000)),
            ],
        ),
    ]
