# Generated by Django 2.2.4 on 2019-09-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190903_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('optiona', models.CharField(max_length=100)),
                ('optionb', models.CharField(max_length=100)),
                ('optionc', models.CharField(max_length=100)),
                ('optiond', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('catagory', models.CharField(choices=[('algorithms', 'Algorithms'), ('database', 'Database Management'), ('hardware', 'Hardware'), ('generalknowledge', 'GeneralKnowledge')], max_length=20)),
            ],
            options={
                'ordering': ('-catagory',),
            },
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
