# Generated by Django 2.2.4 on 2019-10-19 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('quiz', '0003_auto_20190906_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='stu',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='catagory',
            field=models.CharField(choices=[('algorithms', 'Algorithms'), ('database', 'Database Management'), ('hardware', 'Hardware'), ('generalknowledge', 'General Knowledge')], max_length=20),
        ),
    ]
