# Generated by Django 2.2.4 on 2019-10-19 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20191019_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='stu',
            field=models.ForeignKey(default='', max_length=15, on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
