# Generated by Django 2.2.4 on 2019-10-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_questions_stu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='catagory',
            field=models.CharField(choices=[('algorithms', 'Data structure and Algorithms'), ('dm', 'Data Warehousing and Mining'), ('ai', 'Artificial Intelligence'), ('ml', 'Machine Learning'), ('database', 'Database Management'), ('net', 'Communications and Networks'), ('hardware', 'Computer Hardware'), ('generalknowledge', 'General Knowledge'), ('bf', 'Business and Finance'), ('cg', 'Computer graphics and Image Processing'), ('cry', 'Cryptography'), ('cs', 'Cyber-Security'), ('cad', 'Computer Aided Design'), ('os', 'Operating System'), ('sp', 'Signal Processing'), ('rob', 'Robotics'), ('www', 'World Wide Web')], max_length=20),
        ),
    ]
