# Generated by Django 2.2.4 on 2019-08-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('emailid', models.EmailField(max_length=50)),
                ('sapid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('contactno', models.CharField(default=0, max_length=10)),
                ('year', models.CharField(max_length=50)),
            ],
        ),
    ]
